checkout/urls.py
from django.conf.urls import patterns, include, url

from .views import *

urlpatterns = patterns('',
	url(r'^test/(?P<pk>\d+)/$', CheckoutView.as_view() , name = 'checkout'),
	url(r'^p/$', CheckoutView.as_view() , name = 'p'),
	url(r'^t/$', t.as_view() , name = 't'),
)

tasks/urls.py
from django.conf.urls import patterns, include, url

from .views import *

urlpatterns = patterns('',
	url(r'^createtask/$', CreateTaskView.as_view(), name='create_task'),
	
	url(r'^task/(?P<pk>\d+)/$', task_detail_view, name = 'task'),
	url(r'^taskcreator/(?P<pk>\d+)/$', TaskDetailCreatorView.as_view(), name = 'task_detail_creator'),
	url(r'^taskworker/(?P<pk>\d+)/$', TaskDetailWorkerView.as_view(), name = 'task_detail_worker'),
	url(r'^taskuser/(?P<pk>\d+)/$', TaskDetailUserView.as_view(), name = 'task_detail_user'),
	url(r'^taskanonymous/(?P<pk>\d+)/$', TaskDetailView.as_view(), name = 'task_detail'),
	
	url(r'^list/$', TaskListView.as_view(), name='task_list'),
	url(r'^bid/(?P<pk>\d+)/$', CreateBidView.as_view(), name='create_bid'),
	url(r'^heysoulsister/(?P<task_pk>\d+)/(?P<bid_pk>\d+)/$', accept_a_bid_view, name='accept_bid'),
	url(r'^accepttask/(?P<pk>\d+)/$', accept_task_view, name='accept_task' ),

	url(r'^UsersTasks/', UserTaskListView.as_view(), name='user_tasks'),
	url(r'^UsersTasks/(?P<pk>\d+)/$', UserTaskListView.as_view(), name='user_tasks'),
	
	url(r'^completetask/(?P<task_pk>\d+)/(?P<review_pk>\d+)/$', complete_task_view, name='complete_task'),
	url(r'^createreview/(?P<task_pk>\d+)/$', CreateReviewView.as_view(), name='create_review'),

)

users/urls.py
from django.conf.urls import patterns, include, url

from .views import *

urlpatterns = patterns('',
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^byebye/$', PostLogoutView.as_view(), name='post_logout'),
    url(r'^application/$', ApplicationView.as_view(), name='application'),
    url(r'^IWannaWork/$', WorkerApplicationView.as_view(), name='worker_application'),
    url(r'^IWannaStidoe/$', StudierApplicationView.as_view(), name='studier_application'),
    url(r'^MyProfile/$', MyProfileView.as_view(), name='my_profile'),
    url(r'^profile/(?P<pk>\d+)/', ProfileView.as_view(), name='profile'),
    url(r'^createprofile/$', CreateProfileView.as_view(), name='create_profile')
)

workstudy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .views import *

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', HomepageView.as_view(), name='home'),
    url(r'^about/$', AboutUsView.as_view(), name='about_us'),
    url(r'^thankyou/$', ThankYouView.as_view(), name='thanks'),
    
    url(r'^account/', include('users.urls', namespace='users')),
    url(r'^tasks/', include('tasks.urls', namespace='tasks')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),

    
   url(r'^admin/', include(admin.site.urls)),
)

templates/login.html
<h1>Login garuntees entrance to heaven</h1>

<form method="POST" action="{% url 'account:login' %}">

	{% csrf_token %}
	<input type="text" placeholder="Email" id='email' name ='email'>

	<input type="password" placeholder="Password" id='password' name ="password">

	<button type="submit" class="btn btn-success">Sign in</button>
</form>

templates/message.html
{% if messages %}
 	{% for message in messages %}
		{{ message }}
	{%endfor%}
{% endif %}

templates/navbar.html
<head>
    {% load static %}
    <link type="text/css" href="{% static 'css/navbar.css' %}" rel="stylesheet">
    
</head>

<nav id ="square" class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="brand hover" href="{% url 'home' %}">WorkStudie</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav color">
        
        {% if not user.is_authenticated %}
        <a class="brand item" href="{% url 'users:application' %}">Apply</a><
        {% else %}
        
          {% if user.profile %}
            <li><a class="brand item" href="{% url 'users:my_profile' %}">My Profile</a></li>
          {% endif %}
        
        <li><a class="brand item" href="{% url 'tasks:task_list' %}">Tasks</a></li>
        {% endif %}
      
      </ul>
      
      {% if user.is_authenticated %}
        
        {% if not user.profile %}
         
        <form action="{% url 'users:create_profile' %}" class="navabar-form navbar-right">
          <button type="submit" class="userButton btn btn=default button" >Create Profile</button>
        </form>
        
        {% else %}
       
        <form action="{% url 'users:logout' %}" class="navabar-form navbar-right">
          <button type="submit" class="button btn btn=default" >Logout</button>
        </form>
        
        <form  action="{% url 'tasks:create_task' %}" class="navabar-form navbar-right">
          <button type="submit" id="createTask" class="button btn btn=default"  >Create a Task</button>
        </form>

        {% endif %}
      
      {% else %}
             
          <form method="POST" action="{% url 'users:login' %}" class="navbar-form navbar-left" role="form">
            {% csrf_token %}

            <div class="form-group">
              <input type="email" placeholder="Email" id='email' name ='email'class="forms form-control">
            </div>
            
            <div class="forms form-group">
              <input type="password" name='password' placeholder="Password" id='password' class=" forms form-control">
            </div>
            
            <button type="submit" class="button btn btn-success">Sign in</button>
      
      {% endif %}

    </div>
  </div>
</nav>



          

templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>WorkStudy</title>

    <!-- Bootstrap core CSS -->
    <link href="static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="static/styles/cover.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container">
        <h2 class="form-signin-heading">Sign up to be a studier today</h2>
      <form class="form-signin" role="form" action="{% url 'account:signup' %}" method="post">
        {% csrf_token %}
        
        {{ form.as_p }}

        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
      </form>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

templates/t.html
<head>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
	<style type="text/css">
		.red {
			background-color: red
		}

		.blue {
			background-color: blue
		}

		.green {
			background-color: green
		}
	</style>
</head>
<body>

	<div class='red'>
		red
	</div>
	<div class='green'>
		green
	</div>
	<div class='blue'>
		blue
	</div>
	<form action="{% url 'checkout:p' %}" id="payment-form" method="post">
		{% csrf_token %}
		number:	<input class="card-number" type='text'/>
		cvc:	<input class="card-cvc" type='text'/>
		month:	<input class="card-expiry-month" type='text'/>
		year:	<input class="card-expiry-year" type='text'/>
		<div class='payment-errors'>
		</div>
		<button id='token'>token</button>
	</form>
	
	<script type="text/javascript">
		$('#token').click(function(){
			$form = $('#payment-form')
			$form.append($("<input name='life' type=text/>").val('life'));
			$form.append('<h6>' + $('.card-number').val() + '</h6>');
			$form.append('<h6>' + $('.card-cvc').val() + '</h6>');
			$form.append('<h6>' + $('.card-expiry-month').val() + '</h6>');
			$form.append('<h6>' + $('.card-expiry-year').val() + '</h6>');
			Stripe.setPublishableKey('pk_test_pqCDMXXAdmmV0HA01s0w03VS');

			Stripe.card.createToken({
  					number: $('.card-number').val(),
  					cvc: $('.card-cvc').val(),
	  				exp_month: $('.card-expiry-month').val(),
  					exp_year: $('.card-expiry-year').val()
					}, stripeResponseHandler);
			
			function stripeResponseHandler(status, response) {

			if (response.error) {
				    // Show the errors on the form
				    $form.find('.payment-errors').text(response.error.message);
				    $form.find('button').prop('disabled', false);
				    $form.append($('<input type="text" name="stripeToken" />').val('42'));
				    console.log('failed');
				  } else {
				    // response contains id and card, which contains additional card details
				    var token = response.id;
				    console.log(token);
				    // Insert the token into the form so it gets submitted to the server
			    	$form.append($('<input type="text" name="stripeToken" />').val(token));
				    // and submit
				    $form.get(0).submit();
				  }
				};
		})
	</script>
</body>

templates/taskDetail.html
<head>
	{% load static %}
	<title>WorkStudie</title>

	<link type="text/css" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'styles/cover.css' %}" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/taskDetail.css' %}">
</head>

<body>
	<h1>{{ task.title }}</h1>
	<div>
		<p>{{ task.discription }}</p>
		<p> Creator Suggested Price: ${{ task.suggested_price }}</p>
		{% block worker_content %}{% endblock %}
		</br>
		{% block user_actions %}
		{% endblock %}
	</div>
	<div>
			{% if completed %}
					<p><strong>Task has been completed</strong><p>

					<p>
						The winning bid was: {{bid.bid}}
					</p>
			
			{% elif accepted %}
							
				<p>
					<stong>
						Task has been accepted, and the winning bid was
					</stong>
				</p>
				<p>The winning bid was: {{ task.accepted_bid.bid }}</p>
					

			{% else %}
				<p style="text-allign:center; margin-top: 3em;">
					<strong>
						Task has yet to be accepted
					</strong>
				</p>
			{% endif %}
	</div>

<a href="{% url 'task:task_list' %}">
	<div id="home_btn">
		<p class="center" >Return to List</p>
	</div>
</a>
		
	
</body>