tasks/urls.py
from django.conf.urls import patterns, include, url

from .views import *

urlpatterns = patterns('',
	url(r'^createtask/$', CreateTaskView.as_view(), name='create_task'),
	
	url(r'^task/(?P<pk>\d+)/$', task_detail_view, name = 'task'),
	url(r'^taskcreator/(?P<pk>\d+)/$', TaskDetailCreatorView.as_view(), name = 'task_detail_creator'),
	url(r'^taskworker/(?P<pk>\d+)/$', TaskDetailWorkerView.as_view(), name = 'task_detail_worker'),
	url(r'^taskuser/(?P<pk>\d+)/$', TaskDetailUserView.as_view(), name = 'task_detail_user'),
	url(r'^taskanonymous/(?P<pk>\d+)/$', TaskDetailView.as_view(), name = 'task_detail'),
	
	url(r'^list/$', TaskListView.as_view(), name='task_list'),
	url(r'^bid/(?P<pk>\d+)/$', CreateBidView.as_view(), name='create_bid'),
	url(r'^heysoulsister/(?P<task_pk>\d+)/(?P<bid_pk>\d+)/$', accept_a_bid_view, name='accept_bid'),
	url(r'^accepttask/(?P<pk>\d+)/$', accept_task_view, name='accept_task' ),

	url(r'^UsersTasks/', UserTaskListView.as_view(), name='user_tasks'),
	url(r'^UsersTasks/(?P<pk>\d+)/$', UserTaskListView.as_view(), name='user_tasks'),
	
	url(r'^completetask/(?P<task_pk>\d+)/(?P<review_pk>\d+)/$', complete_task_view, name='complete_task'),
	url(r'^createreview/(?P<task_pk>\d+)/$', CreateReviewView.as_view(), name='create_review'),

)

users/urls.py
from django.conf.urls import patterns, include, url

from .views import *

urlpatterns = patterns('',
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^byebye/$', PostLogoutView.as_view(), name='post_logout'),
    url(r'^application/$', ApplicationView.as_view(), name='application'),
    url(r'^IWannaWork/$', WorkerApplicationView.as_view(), name='worker_application'),
    url(r'^IWannaStidoe/$', StudierApplicationView.as_view(), name='studier_application'),
    url(r'^MyProfile/$', MyProfileView.as_view(), name='my_profile'),
    url(r'^profile/(?P<pk>\d+)/', ProfileView.as_view(), name='profile'),
    url(r'^createprofile/$', CreateProfileView.as_view(), name='create_profile')
)

workstudy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .views import *

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', HomepageView.as_view(), name='home'),
    url(r'^about/$', AboutUsView.as_view(), name='about_us'),
    url(r'^thankyou/$', ThankYouView.as_view(), name='thanks'),
    
    url(r'^account/', include('users.urls', namespace='users')),
    url(r'^tasks/', include('tasks.urls', namespace='tasks')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),

    
   url(r'^admin/', include(admin.site.urls)),
)

users/models.py
import datetime

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.urlresolvers import reverse

# Create your models here.class UserManager(BaseUserManager):
class Profile(models.Model):
	"""
	Represents every users profile.
	"""
	#All the task that have been made by this user
	tasks_made = models.ManyToManyField('tasks.Task', related_name='task_made')
	#All the task that have been completed by the user
	tasks_completed = models.ManyToManyField('tasks.Task', related_name='tasks_completed')
	#Discription of what skills that have
	description = models.TextField(max_length='1000', blank=True)
	#Intended Major
	intended_major = models.CharField(max_length=255, blank=True, default="Life")
	#The users profile
	user = models.OneToOneField('users.User' ,blank=True, null=True)

	#Returns unicode and includes pk so I can easily look up the profile if need be
	def __unicode__(self):
		return str(self.pk) + ' ' + self.user.first_name + ' ' + self.user.last_name + "'s Profile"

	def get_absolute_url(self):
		return reverse('users:profile', kwargs={'pk':self.pk}) 

class UserManager(BaseUserManager):	
	"""
	Stolen code from online
	"""

	def create_user(self, email, first_name='John',last_name='Doe', password= None):
		if not email:
			raise ValueError('User must have email')

		user = self.model(
			email=self.normalize_email(email),
			first_name=first_name,
			last_name=last_name,
		)

		user.set_password(password)
		user.save()
		return user

	def create_superuser(self, email, password, first_name='', last_name=''):
		user = self.create_user(email, first_name, last_name, password=password)
		user.is_admin = True
		user.is_superuser = True
		user.is_worker = True
		user.is_active = True
		user.save()
		return user

class User(AbstractBaseUser, PermissionsMixin):
	"""
	Represents every user just with different permissions
	"""
	#date that user join
	creation_date = models.DateTimeField(auto_now_add=True, auto_now=False, editable=False)
	email = models.EmailField(max_length=100, unique=True, primary_key=True)
	first_name = models.CharField(max_length=255, default='John')
	last_name = models.CharField(max_length=100, default='Doe')
	is_active = models.BooleanField(default=False)
	merchant_account_id = models.CharField(max_length=255, null=True)
	
	is_admin = models.BooleanField(default=False)
	is_worker = models.BooleanField(default=False)
	email_notifactions = models.BooleanField(default=True)
	is_superuser = False
	
	objects = UserManager()

	USERNAME_FIELD = 'email'

	def get_full_name(self):
		return self.first_name +' ' + self.last_name

	def get_short_name(self):
		return self.first_name

	def __unicode__(self):
		return self.email

	@property
	def is_staff(self):
		return self.is_superuser		

users/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import	User, Profile


class UserCreationForm(forms.ModelForm):
	"""
	Stolen code from django tutorial
	"""
	password1 = forms.CharField(label='password',
		widget = forms.PasswordInput)
	password2 = forms.CharField(label='repeat password',
		widget = forms.PasswordInput)

	class Meta:
		model =	User
		fields = ('email', 'first_name', 'last_name')

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')

		if password1 and password2 and password2 != password1:
			raiseforms.ValidationError('passwords do not match')
		return password2

	def save(self, commit=True):
		user = super(UserCreationForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user

class UserChangeForm(forms.ModelForm):
	"""
	Stolen code from django tutorial
	"""
	password = ReadOnlyPasswordHashField()

	class Meta:
		model =	User
		fields = ('email', 'password', 'first_name', 'last_name', 'is_active',
			'is_superuser', 'is_worker')

	def clean_password(self):
		return self.initial['password']

class ProfileCreationForm(forms.ModelForm):
	"""
	Creates a user profile
	"""
	class Meta:
		model = Profile
		fields = ['description', 'intended_major']

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.core.mail import mail_admins
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.shortcuts import render, render_to_response, RequestContext, redirect
from django.utils.datastructures import MultiValueDictKeyError 


from .forms import UserCreationForm, ProfileCreationForm
from .models import Profile, User

def logout_view(request):
	"""
	Will logout the user and redirect to the homepage
	"""
	logout(request)
	messages.success(request, "Why would you ever log out? That's it I'm giving you a computer virus")
	return HttpResponseRedirect(reverse('home'))

"""
You need to send and email with a link to a user authentication page
in order to confirm valid email
"""
class ApplicationView(View):
	"""
	Is an application do joine workstudie, I think everything is really completed in the worker application
	and the studier application.
	"""
	template_name = "application.html"

	def get(self, request, *args, **kwargs):
		return render(request, self.template_name, {})

class StudierApplicationView(View):
	"""
	An application for a studier to just workstudie
	"""
	template_name = 'applicationStudier.html'
	form = UserCreationForm

	def get(self, request, *args, **kwargs):
		return render(request, self.template_name, {'form': self.form})

	def post(self, request, *args, **kwargs):
		form = self.form(request.POST or None)

		if form.is_valid():
			save_it = form.save(commit=True)
			save_it.save()
			mail_admins(
				'Studier Application', 
				'%s wants to become a studier. Their email is %s' % (save_it.first_name, save_it.email),
				fail_silently=False,
				)
			messages.success(request, 'thanks for joining asshole')
			return HttpResponseRedirect(reverse('account:thanks'))

class WorkerApplicationView(View):
	"""
	An application to just workstudie as a worker
	"""
	template_name = 'applicationWorker.html'
	form = UserCreationForm

	def get(self, request, *args, **kwargs):
		return render(request, self.template_name, {'form': self.form})

	def post(self, request, *args, **kwargs):
		form = self.form(request.POST or None)

		if form.is_valid():
			save_it = form.save(commit=True)
			save_it.save()
			mail_admins(
				'Worker Application', 
				'%s wants to become a worker. Their email is %s' % (save_it.first_name, save_it.email),
				fail_silently=False,
				)
			messages.success(request, 'thanks for joining asshole')
			return HttpResponseRedirect(reverse('account:thanks'))

		messages.error(request, 'There was a problem with your application')
		return HttpResponseRedirect(reverse('account:thanks'))

class LoginView(View):
	"""
	Logs user into the website
	"""
	template_name = 'login.html'

	def get(self,request):
		return render (request, self.template_name, {})

	def post(self, request, *args, **kwargs):
		username = request.POST['email']
		password = request.POST['password']

		user = authenticate(username=username, password=password)

		if user is not None:
			if user.is_active:
				login(request, user)
				messages.success(request, 'YOU DID IT! YOU LOGGED IN! I KNEW YOU COULD DO IT! I BET YOUR MOTHER IS SO PROUD!!!')
				return HttpResponseRedirect(reverse('home'))
			else:
				messages.success(request, "UH OH! you ain't active please leave")
				return HttpResponseRedirect(reverse('home'))

		else:
			messages.success(request, 'UH OH! you did something wrong please leave')
			return HttpResponseRedirect(reverse('home'))


class PostLogoutView(TemplateView):
	"""
	This is where all logoed out users get redirected
	"""
	template_name = 'logout.html'

class ThankYouView(TemplateView):
	"""
	Standard thank you page that is used for most thank users for differnt things with
	custom messages.
	"""
	template_name = 'thankyou.html'

class CreateProfileView(View):
	"""
	A view that allows the user to create his or her profile
	"""
	form = ProfileCreationForm
	template_name = 'createProfile.html'

	@method_decorator(login_required)
	def get(self, request):
		return render(request, self.template_name, {'form' : self.form})

	@method_decorator(login_required)
	def post(self, request, *args, **kwargs):
		form = self.form(request.POST or None)
		if form.is_valid():
			user = request.user
			save_it = form.save(commit=False)
			user.profile = save_it
			save_it.save()
			user.save()
			messages.success(request, "You created your profile")
			return HttpResponseRedirect(reverse('account:thanks'))


class MyProfileView(View):
	"""
	Shows the user profile
	"""
	template_name = 'profile.html'

	def get(self, request):
		user = request.user
		if user.profile== None:
			HttpResponseRedirect(reverse('account:create_profile'))
		profile = user.profile
		number_of_completed_task = profile.tasks_completed.count()
		number_of_task_made = profile.tasks_made.count()
		context = {'user': user, 
			'profile':profile,
			'major':profile.intended_major,
			'tasks_completed' : number_of_completed_task,
			'tasks_made' : number_of_task_made
			}
		return render(request, self.template_name, context)

class ProfileView(DetailView):
	"""
	This calss might be excessive not sure yet tho so I'lll leave it
	Not entirely postive what it's for
	"""
	model = Profile
	template_name = 'profile.html'

	def get_context_data(self, **kwargs):
		context = super(ProfileView, self).get_context_data(**kwargs)
		profile = Profile.objects.get(pk = self.kwargs['pk'])
		user = profile.user
		number_of_completed_task = profile.tasks_completed.count()
		number_of_task_made = profile.tasks_made.count()
		context = {'user': user, 
			'profile':profile,
			'major':profile.intended_major,
			'tasks_completed' : number_of_completed_task,
			'tasks_made' : number_of_task_made
			}
		return context

templates/users/application.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>WorkStudy</title>

    <!-- Bootstrap core CSS -->
    <link href="static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="static/styles/cover.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container">
        <ul>
          <li><a href="{% url 'users:studier_application' %}"<h2 class="form-signin-heading">Apply to be a studier today</h2></a></li>
          <li><a href="{% url 'users:worker_application' %}"><h2>Apply to be a worker today</h2></a></li>
        </ul>
     
      {% block user_application  %}
      {% endblock %}

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

templates/users/applicationStudier.html
{% extends 'users/application.html' %}
{% block user_application %}
	<form class="form-signin" role="form" action="{% url 'users:studier_application' %}" method="post">
        {% csrf_token %}
        
        {{ form.as_p }}

        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
      </form>
{% endblock %}

templates/users/applicationWorker.html
{% extends 'users/application.html' %}
{% block user_application %}
	<form class="form-signin" role="form" action="{% url 'users:worker_application' %}" method="post">
        {% csrf_token %}
        
        {{ form.as_p }}

        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
      </form>
{% endblock %}

templates/users/createProfile.html
<h1>Create a Profile!</h1>
<form method="POST" action="{% url 'users:create_profile' %}">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Submit</button>
</form>

templates/users/login.html
<h1>Login garuntees entrance to heaven</h1>

<form method="post" action="{% url 'account:login' %}">

	{% csrf_token %}
	<input type="text" placeholder="Email" id='email' name ='email'>

	<input type="password" placeholder="Password" id='password' name ="password">

	<button type="submit" class="btn btn-success">Sign in</button>
</form>

templates/users/logout.html
<h1>GoodBye World!</h1>

templates/users/profile.html
<head>
	<title>{{ users.first_name }} {{ users.last_name }}</title>
</head>

<body>
	{% if users.is_worker %}
		<div>
			<h3>
				Worker: {{ users.first_name }} {{ users.last_name }}
			</h3>
		</div>
	{% else %}
		<div>
			<h3>
				Studier: {{ users.first_name }} {{ users.last_name }}
			</h3>
		</div>
	{% endif %}
	<ul>
		{% if users.is_worker %}
			<li> Task Completed: {{ tasks_completed }} </li>
		{% endif %}
		<li>Majoring in: {{ major }}</li>
		<a href="{% url 'tasks:user_tasks' pk=profile.pk %}"><li>Task Made: {{ tasks_made }}</li></a>
	</ul>

	<div>
		<p>
			<h4>Description: </h4>
			{{ profile.description }}
		</p>
	</div>
</body>