tasks/urls.py
from django.conf.urls import patterns, include, url

from .views import *

urlpatterns = patterns('',
	url(r'^createtask/$', CreateTaskView.as_view(), name='create_task'),
	
	url(r'^task/(?P<pk>\d+)/$', task_detail_view, name = 'task'),
	url(r'^taskcreator/(?P<pk>\d+)/$', TaskDetailCreatorView.as_view(), name = 'task_detail_creator'),
	url(r'^taskworker/(?P<pk>\d+)/$', TaskDetailWorkerView.as_view(), name = 'task_detail_worker'),
	url(r'^taskuser/(?P<pk>\d+)/$', TaskDetailUserView.as_view(), name = 'task_detail_user'),
	url(r'^taskanonymous/(?P<pk>\d+)/$', TaskDetailView.as_view(), name = 'task_detail'),
	
	url(r'^list/$', TaskListView.as_view(), name='task_list'),
	url(r'^bid/(?P<pk>\d+)/$', CreateBidView.as_view(), name='create_bid'),
	url(r'^heysoulsister/(?P<task_pk>\d+)/(?P<bid_pk>\d+)/$', accept_a_bid_view, name='accept_bid'),
	url(r'^accepttask/(?P<pk>\d+)/$', accept_task_view, name='accept_task' ),

	url(r'^UsersTasks/', UserTaskListView.as_view(), name='user_tasks'),
	url(r'^UsersTasks/(?P<pk>\d+)/$', UserTaskListView.as_view(), name='user_tasks'),
	
	url(r'^completetask/(?P<task_pk>\d+)/(?P<review_pk>\d+)/$', complete_task_view, name='complete_task'),
	url(r'^createreview/(?P<task_pk>\d+)/$', CreateReviewView.as_view(), name='create_review'),

)

workstudy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .views import *

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', HomepageView.as_view(), name='home'),
    url(r'^about/$', AboutUsView.as_view(), name='about_us'),
    url(r'^thankyou/$', ThankYouView.as_view(), name='thanks'),
    
    url(r'^account/', include('users.urls', namespace='users')),
    url(r'^tasks/', include('tasks.urls', namespace='tasks')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),

    
   url(r'^admin/', include(admin.site.urls)),
)

tasks/models.py
import datetime

from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone

class IntegerRangeField(models.IntegerField):
	"""
	A integer field that can only have a value between a given min and max
	"""
	def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
		self.min_value, self.max_value = min_value, max_value
		models.IntegerField.__init__(self, verbose_name, name, **kwargs)
	def formfield(self, **kwargs):
		defaults = {'min_value': self.min_value, 'max_value':self.max_value}
		defaults.update(kwargs)
		return super(IntegerRangeField, self).formfield(**defaults)

from south.modelsinspector import add_introspection_rules
add_introspection_rules([
        (
            (IntegerRangeField, ),
            [],
            {
                "verbose_name": ["verbose_name", {"default": None}],
                "name":         ["name",         {"default": None}]
            },
        ),
    ], ["^tasks\.models\.IntegerRangeField"])

class Review(models.Model):
	"""
	A review for a worker or studier meant to be compeleted after every task.
	"""
	#the rating of the opposite party
	rating = IntegerRangeField(min_value=1, max_value=10)
	#Any extra cmments thhey may have
	comments = models.TextField(max_length=1000, blank=True)
	#the Creator the review
	creator = models.ForeignKey('users.User', related_name="review_creator",
	 null=True, blank=True)

	def __unicode__(self):
		return self.creator

class Bid(models.Model):
    """
    Bid is used to bid on a task if for example the suggested price was set too 
    high by the worker or there is no suggested price.
    """
    #Bidding price
    bid = models.DecimalField(max_digits=5, decimal_places=2)
	#The bidder
    bidder = models.ForeignKey('users.User', null=False, blank=False)
	#A message meant for the creator about why there qualified or any specail conditions or anything really
    message = models.TextField(max_length=140, blank=True)
    #The task being bidded on
    task = models.ForeignKey('tasks.Task', related_name='bids') 

    def __unicode__(self):
        return self.bidder


class Task(models.Model):
    """
    A task is the foundation of this site represents a task posted by a studier
    that needs to be complted.
    """
    #Title of the task
    title = models.CharField(blank=False, max_length=75)
	#discription of the actual task
    discription = models.TextField(blank=False, max_length=420) 
	#the price that the studier is willing to pay, not necessairly maximum price
    suggested_price = models.DecimalField(max_digits=5, decimal_places=2, blank=True)
	
	#Boolean field should be false until a worker accpets the task
    accepted = models.BooleanField(default=False)
	#Boolean fileds should reamin false until the task is completed and transation is done
    completed = models.BooleanField(default=False)
	#Foreign Key represents the author of the tasks
    creator = models.ForeignKey('users.User', related_name='task_creator')
	#A foreign ket that represents only the worker who has accpeted the task
    worker = models.ForeignKey('users.User', limit_choices_to={'is_worker' : True}, related_name='task_worker', null=True, blank=True)
	
	#A field to represent the selected bid for the task
    accepted_bid = models.ForeignKey(Bid, related_name='accepted_bid', null=True, blank=True)
	#Review given made by the worker about the creator
    review_of_worker = models.ForeignKey(Review, related_name='task_worker_review', null=True, blank=True)
	#review made by the creator about the worker
    review_of_creator = models.ForeignKey(Review, related_name='task_create_review', null=True, blank=True)

	#date created
    creation_date = models.DateTimeField(auto_now_add=True, auto_now=False, editable=False, null=True)
	#the date that the task was accepted
    acception_date = models.DateTimeField(auto_now_add=False, auto_now=False, null=True)
	#the date that the task was completed
    completion_Date = models.DateTimeField(auto_now_add=False, auto_now=False, null=True)

    def accept_bid(self,bid):
        if self.accepted_bid:
            raise ValidationError('a bid has already been accepted')
        else:
            self.accepted_bid = bid
            self.worker = bid.bidder
            self.accepted = True
            self.accepted_date = datetime.datetime.utcnow().replace(tzinfo=timezone.utc)
            self.save()
            return True

	#returns url of the detail view for the task	
    def get_absolute_url(self):
        return reverse('tasks:task', kwargs={'pk' : self.pk})

    def __unicode__(self):
        return self.title

tasks/forms.py
from django import forms

from .models import Task, Bid, Review

class CreateTaskForm(forms.ModelForm):
	"""
	Creates a Task
	"""
 	class Meta:
 		model = Task
 		fields = ['title', 'discription', 'suggested_price']

class CreateBidForm(forms.ModelForm):
	"""
	Creates a bid.
	"""
 	class Meta:
 		model = Bid
 		fields = ['bid', 'message']

class CreateReviewForm(forms.ModelForm):
	"""
	Creates a review.
	"""
	class Meta:
		model = Review
		fields = ['rating', 'comments']

tasks/views.py
import datetime

from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import UpdateView

from .forms import CreateTaskForm, CreateBidForm, CreateReviewForm
from .models import Task, Bid, Review
from users.models import Profile 
from workstudy.settings import EMAIL_HOST_USER

#view used when a studier accepts a given bid
@login_required
def accept_a_bid_view(request, **kwargs):
    """
    Function is run in order to accept a bid. It the user is not the creator
    of the task it should throw an error. Also will send creator an email
    notifying them that their bid was accepted and they should promptly completely
    the task.
    """
    task=Task.objects.get(pk=kwargs['task_pk'])
    
    if task.creator == request.user:
        bid = Bid.objects.get(pk=kwargs['bid_pk'])
        ok = task.accept_bid(bid)
        if ok:
            messages.success(request,"Congrats you've accepted a bid I'm proud of you")
            if bid.bidder.email_notifactions:
                 send_mail('WorkStudie Notification',
                        "Someone accepted your bid. Head over to WorkStudie.com to check it out",
                        EMAIL_HOST_USER,
                        [task.creator.email],
                        fail_silently=False)
            return HttpResponseRedirect(reverse('tasks:task_list'))
        else:    
            messages.error(request, 
            """
            There was a problem accepted your task, most likely another bid
            was already accepted but if you don't believe this to be the case
            please try again. If porblem continues contact workstudie@gmail.com.
            """)
            return HttpResponseRedirect(reverse('home'))

    else:
        messages.error(request, """It looks as if this task has already been accepted
         or maybe you're not the creator, but why would you being clicking 
         buttons then... (The NSA is watchig you)
         """)
        return HttpResponseRedirect(reverse('home'))

#View run when a task is outright accepted with out a bid or anything just accepted as is (worker would accept a task then this view woul run)
@login_required
def accept_task_view(request, **kwargs):
    """
    This function is run when a worker accepts a task just as the studier required and
    at the studier's suggested price. The Studier should be notfied that their task was
    accepted and a work will complete promptly.
    """
    if request.user.is_worker:
        task = Task.objects.get(pk=kwargs['pk'])
        bid = Bid.objects.create(
            task=task,
            bidder=request.user,
            bid = task.suggested_price,
            message = "This task was accepted by a worker as is, with no conditions attached."
            )
        task.accept_bid(bid)
        if task.creator.email_notifactions:
            send_mail('WorkStudie Notification',
                    "Someone accepted your task and it should be completely promptly. Head over to WorkStudie.com to check it out",
                    EMAIL_HOST_USER,
                    [task.creator.email],
                    fail_silently=False) #Eventually I should changethis to True it's a minor thing not getting a notifaction and it'd be even more annoying to get an error message when the user is using the website
            messages.success(request,"You have taken on this task, please completely in a timely fasion.")
        return HttpResponseRedirect(reverse('home')) #Eventually this should be some sort of success page
    
    else:
        messages.error(request, "You are not worker therefore you're not allowed to accept the task")
        return HttpResponseRedirect(reverse('home'))# """I would like to change this at some point but for now it'll do later we can redirect to a differnt page"""

#creates a bid in order to bid on a task
class CreateBidView(View):
    """
    View used for a worker creating a bid on a specfic task. 
    """

    form = CreateBidForm
    template_name = "tasks/createBid.html"

    @method_decorator(login_required)
    def get(self, request, **kwargs):
        if request.user.is_worker:
            context = {'pk':kwargs['pk'], 'form':self.form}
            return render(request, self.template_name, context)
        else:
            raise PermissionDenied("Only wokers can bid on task")


    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        if request.user.is_worker:
            form = self.form(request.POST or None)
            if form.is_valid():
                task = Task.objects.get(pk=kwargs['pk'])
                save_it = form.save(commit=False)
                save_it.bidder = request.user
                save_it.task = task
                save_it.save()

                if task.creator.email_notifactions:
                    send_mail('WorkStudie Notification',
                        "Someone bidded on your task. Head over to WorkStudie.com to check it out",
                        EMAIL_HOST_USER,
                        [task.creator.email],
                        fail_silently=False)

                return HttpResponseRedirect(reverse('home'))
            else:
                messages.error(request,
                        """
                        Form was in valid please try again. If porblem continues
                        please contact workstudie@gmail.com.
                        """)
                return HttpResponseRedirect(reverse('tasks:create_bid',
                    kwargs={'pk':kwargs['pk']}))
        else:
            raise PermissionDenied("Only workers can bid on task")

#View that is run when a task is completed need to redirect to checkout
@login_required
def complete_task_view(request, **kwargs):
    """
    Completes the task and eventually should redirect to the payment processing
    Both the worker and the studier must complete the task it also redirects them 
    to the review page where both worker and studier review each other.
    """

    task=task.objects.get(pk=kwargs['task_pk'])
    if task.accepted == True and task.accepted_bid != None:
        
        if task.creator == request.user:
            if not task.review_of_worker:
                messages.error("Please complete review")
                return HttpResponseRedirect(reverse('tasks:create_review'))
            task.completed = True
            review = Review.objects.get(pk=kwargs['review_pk'])
            task.worker_review = review
            task.completed_date = datetime.datetime.utcnow().replace(tzinfo=timezone.utc)
            task.save()

            return HttpResponseRedirect(reverse('tasks:review', kwargs={'task_pk' : kwargs['task_pk']}))
        
        elif task.worker == request.user:
            
            if not task.review_of_creator:
                message.error("Please complete review")
                return HttpResponseRedirect(reverse('tasks:create_review'))
            review = Review.objects.get(pk=kwargs['review_pk'])
            task.creator_review = review
            task.completed_date = datetime.datetime.utcnow().replace(tzinfo=timezone.utc)
            task.save()
            task.worker.profile.task_completed.add(task)
            return HttpResponseRedirect(reverse('tasks:review', kwargs={'task_pk' : kwargs['task_pk']}))
        
        else:
            
            messages.error(request, "You do not have permission to compelte task")
            return HttpResponseRedirect(reverse('home'))
    else:   
        messages.error(request, "Bid has not acceted yet")
        HttpResponseRedirect(reverse('home'))

#This view is used when a task is completed and users are prompted to review each other
class CreateReviewView(View):
    """
    This view is used to create a new review on a worker or studier based on how well they
    performed or how conciderate they were when doing the task.
    """
    form = CreateReviewForm
    template_name = 'tasks/createReview.html'

    @method_decorator(login_required)
    def get(self, request, **kwargs):
        return render(request,self.template_name, {'form': self.form, 'task_pk' : kwargs['task_pk']})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        task = Task.objects.get(pk=kwargs['task_pk'])
        if request.user != task.worker and request.user != task.creator:
            raise PermissionDenied("You are not allowed to review this task")
        form = self.form(request.POST or None)
        if form.is_valid():
            save_it = form.save(commit=False)
            save_it.creator = request.user
            save_it.save()
            task = Task.objects.get(pk=kwargs['task_pk'])
            if request.user == task.worker:
                task.review_of_creator= save_it
                task.save()
            else :
                task.review_of_worker = save_it
                task.save()
            return HttpResponseRedirect(reverse('tasks:task', kwargs={'pk':kwargs['task_pk']}))
        messages.error(request,
                """
                There's been a mistaek with your review, please try again, if
                there continues to be a problem please email WorkStudie@gmail.com
                """
                )
        return HttpResponseRedirect(reverse('tasks:task', kwargs={'pk':kwargs['task_pk']}))

    

#View used to create task
class CreateTaskView(View):
    """
    View used to create a task.
    """
    form = CreateTaskForm

templates/tasks/createBid.html
{{ form.as_p }}

templates/tasks/createReview.html
<h1>Review</h1>
<form method="POST" action="{% url 'tasks:create_review' task_pk=task_pk %}">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> submit</button>
</form>

templates/tasks/createTask.html
<form action="{% url 'tasks:create_task' %}"  method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

templates/tasks/taskDetail.html
<head>
    <title>WorkStudie</title>
</head>
<html>
    <nav>
        <ul>
            <li><a>WorkStudie</a></li>
            <li><a>Tasks</a></li>
            <li><a>Profile</a></li>
            <div>
                <li><a>Sign in</a></li>
            </div>
        </ul>
    </nav>
    <body>
        <div>
            <h1>Task Description</h1>
            <p>
                Generic discription being placed here purely so I can look at it
                and see what it's like to have a full page of text. You know What
                I'm saying do you watch Trailer Park Boys?
            </p>
            <h5>10.00</h5>
            <h6>Lowest Bid</h6>
        </div>
        <div>
            <a>Worker Actions</a>
        </div>
    </body>
</html>
<!--
<head>
	{% load static %}
	<title>WorkStudie</title>

	<link type="text/css" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <!--<link href="{% static 'styles/cover.css' %}" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/taskDetail.css' %}">
</head>

<body>
	<h1>{{ task.title }}</h1>
	<a href="{{ task.creator.profile.get_absolute_url }}"><h3>Creator: {{task.creator.first_name}} {{task.creator.last_name}}</h3></a>
	<div>
		<p>{{ task.discription }}</p>
		<p> Creator Suggested Price: ${{ task.suggested_price }}</p>
		{% block worker_content %}{% endblock %}
		</br>
		{% block user_actions %}
		{% endblock %}
	</div>
	<div>
			{% if completed %}
					<p><strong>Task has been completed</strong><p>

					<p>
						The winning bid was: {{bid.bid}}
					</p>
			
			{% elif accepted %}
							
				<p>
					<stong>
						Task has been accepted, and the winning bid was
					</stong>
				</p>
				<p>The winning bid was: {{ task.accepted_bid.bid }}</p>
					

			{% else %}
				<p style="text-allign:center; margin-top: 3em;">
					<strong>
						Task has yet to be accepted
					</strong>
				</p>
			{% endif %}
	</div>

<a href="{% url 'tasks:task_list' %}">
	<div id="home_btn">
		<p class="center" >Return to List</p>
	</div>
</a>
		
	
</body>
!-->

templates/tasks/taskDetailCreator.html
{% extends 'tasks/taskDetail.html' %}

{% block user_actions %}
	{% if bid %}
		{% load static %}
		 <link type="text/css" href="{% static 'css/task_list.css' %}" rel="stylesheet"/>
		
		{% if not accepted %}
			{% for bid in bids %}
				<div>
					<form method="GET" action="{% url 'tasks:accept_bid' task_pk=task.pk bid_pk=bid.pk %}">
						{% csrf_token %}	
						<button type="submit" class="btn btn-success">Accept Bid</button>
					</form>
				</div>
			{% endfor %}
		{% elif not completed %}
			<div>
				<form action="{% url 'tasks:create_review' task_pk=task_pk %}">
				{% csrf_token %}
			
					<button type="submit" class="btn btn-success">Complete Task</button>
				</form>
			</div>
		{% endif %}
	
	{% else%}
	
		<p class="center"><strong>There are currently no bids</strong></p>
	
	{% endif %}
{% endblock %}

templates/tasks/taskDetailWorker.html
{% extends 'tasks/taskDetail.html' %}
{% block user_actions %}
	{% if accepted %}
		<form method="POST" action="{% url 'tasks:create_review' task_pk=task.pk %}">
			{% csrf_token %}	
			<button type="submit" class="btn btn-success">Complete Task</button>
		</form>
	{% else %}

		

		<form method="POST" action="{% url 'tasks:accept_task' pk=task.pk %}">
			{% csrf_token %}
			<button type="submit" class="btn btn-success">ACCEPT TASK AS IS</button>
		</form>


		<a href="{% url 'tasks:create_bid' task.pk %}"><button type="submit" class="btn btn-success">Bid</button></a>
	{% endif %}
{% endblock %}

templates/tasks/taskList.html
<head>
    <Title>WorkStudie</Title>
</head>
<html>
    <nav>
        <ul>
            <li><a>WorkStudie</a></li>
            <li><a>Tasks</a></li>
            <li><a>Profile</a></li>
            <div>
                <li><a>Sign in</a></li>
            </div>
        </ul>
    </nav>
    <body>
        <h1>Available Task</h1>
        <div>
            <h2>Title of Task</h2>
            <p>
                Description (fake one purely for size) So hey guys my name
                is Adam I'm just a normal college person I like bacon
            </p>
        </div>
        <div>
            <h2>Title of Task</h2>
            <p>
                Description (fake one purely for size) So hey guys my name
                is Adam I'm just a normal college person I like bacon
            </p>
        </div>
        <div>
            <h2>Title of Task</h2>
            <p>
                Description (fake one purely for size) So hey guys my name
                is Adam I'm just a normal college person I like bacon
            </p>
        </div>
        <div>
            <h2>Title of Task</h2>
            <p>
                Description (fake one purely for size) So hey guys my name
                is Adam I'm just a normal college person I like bacon
            </p>
        </div>
        <div>
            <h2>Title of Task</h2>
            <p>
                Description (fake one purely for size) So hey guys my name
                is Adam I'm just a normal college person I like bacon
            </p>
        </div>
        <div>
            <h2>Title of Task</h2>
            <p>
                Description (fake one purely for size) So hey guys my name
                is Adam I'm just a normal college person I like bacon
            </p>
        </div>
    </body>
    <footer>
        <a>Email us with question, comments, or concerns at WorkStudie@gmail.com</a>
    </footer>
</html>

<!--
<head>
	{% load static %}
	<title>WorkStudie</title>
	
	<link type="text/css" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">!-->
    <!-- Custom styles for this template -->
    <!--<link href="{% static 'styles/cover.css' %}" rel="stylesheet">

    <link type="text/css" href="{% static 'css/task_list.css' %}" rel="stylesheet"/>
</head>
<body>


<h1>All Avaible task in your area</h1>

<ul>

	{% for task in object_list %}
   		<div>
   		 	<a href="{{ task.get_absolute_url }}"><h3>{{ task.title }}</h3>

   		 	<p>{{ task.discription }}</p></a>
   		</div>
	{% empty %}
    	<li>No task yet.</li>
{% endfor %}
</ul>


<a href="{% url 'home' %}">
	<div id="home_btn">
		<p>Return Home</p>
	</div>
</a>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
</body>
!-->